version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./init.sh:/init.sh
    entrypoint: sh -c "/init.sh"
    ports:
      - 80:80
      - 443:443